from flask import Flask, render_template, request
import json
import random
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import joblib
from nlp_helper import analyze_input, train_model

app = Flask(__name__)

# Load the response data
with open('json/data.json', 'r') as file:
    responses = json.load(file)

def get_response(intent):
    if intent == "greeting":
        return random.choice(responses["greetings"])
    elif intent == "well_being":
        return random.choice(responses["well_being"])
    elif intent == "not_well":
        return "I'm sorry to hear that. How can I help you feel better?"
    elif intent == "farewell":
        return random.choice(responses["farewell"])
    elif intent == "request_help":
        return "Sure! What do you need help with?"
    elif intent == "gratitude":
        return "You're welcome! I'm here to help."
    elif intent == "check_wellbeing":
        return "I'm just a bot, but I'm functioning well! How about you?"
    elif intent == "ask_name":
        return "I’m a chatbot and I don’t have a name, but you can call me Assistant!"
    elif intent == "request_info":
        return "What would you like to know more about?"
    elif intent == "fever":
        return "First Aid for Fever\n\nStep by Step First Aid Instructions:\n\n1. Take the Person’s Temperature: Use a thermometer to accurately measure the person’s temperature. A fever is usually defined as a temperature over 100.4°F(38°C).\n\n2. Keep the Person Hydrated: Encourage the person to drink plenty of fluids (water,electrolyte drinks,or clear broth) to prevent dehydration.\n\n3. Help the Person Rest: Encourage rest in a cool, comfortable environment.\n\n4. Use a Cool Compress: Apply a cool, damp cloth to the person’s forehead.\n\n5. Administer Over the Counter Fever Reducers\n"
    elif intent == "chemical_burns":
        return "First Aid for Chemical Burns\n\nStep by Step First Aid Instructions:\n\n1. Remove the Chemical Source: If possible, safely remove the person from the source of the chemical. Be cautious not to come into contact with the chemical yourself.\n\n2. Flush the Burn with Water: Immediately flush the affected area with cool running water for at least 20 minutes to remove the chemical. Do not use a strong stream of water as this can further damage the tissue.\n\n3. Remove Contaminated Clothing: Carefully remove any clothing or jewelry that has been contaminated by the chemical to prevent further exposure.\n\n4. Avoid Using Ointments or Lotions: Do not apply any ointments, lotions, or remedies to the burn unless instructed by a medical professional.\n\n5. Cover the Burn: Loosely cover the burn with a sterile, non-stick bandage or clean cloth. Avoid tight wrapping.\n\n6. Seek Medical Attention: If the burn is severe, covers a large area, or affects the eyes, face, groin, or major joints, seek emergency medical help immediately.\n\nRecommended Medications for Chemical Burns:\n- Topical Antibiotics: Such as silver sulfadiazine, prescribed by a doctor to prevent infection.\n- Pain Relievers: Over-the-counter medications like ibuprofen or acetaminophen can help manage pain.\n\nIndication of Nearby Hospital: If the chemical burn is severe or affects sensitive areas, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "drowning":
        return "First Aid for drowning\n\nStep by Step First Aid Instructions:\n\n1. Get the Person Out of the Water: If it's safe for you, remove the person from the water as quickly as possible.\n\n2. Call Emergency Services: Immediately call for emergency help while others assist with the person’s rescue.\n\n3. Check for Breathing and Pulse: If the person is unconscious but breathing, lay them on their side in the recovery position. If the person is not breathing, begin CPR immediately.\n\n4. Perform CPR (if necessary): Start with chest compressions (30 compressions at a rate of 100-120 per minute), followed by two rescue breaths. Continue CPR until the person starts breathing or emergency services arrive.\n\n5. Keep the Person Warm: After rescue, cover the person with a blanket or dry clothing to prevent hypothermia.\n\n6. Seek Medical Attention: Even if the person seems to recover, they may have inhaled water, which can lead to secondary drowning. Medical evaluation is essential.\n\nRecommended Medications for Drowning:\n- Oxygen: Administered by medical professionals at the scene or hospital.\n-Other Treatments: Medications may be administered at the hospital depending on complications like infection or respiratory issues.\n\nIndication of Nearby Hospital: After any drowning incident, medical evaluation is crucial. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "allergic_reactions":
        return "First Aid for Allergic Reactions\n\nStep by Step First Aid Instructions:\n\n1. Identify the Symptoms: Look for signs such as hives, itching, swelling (especially of the face, lips, or throat), difficulty breathing, nausea, or vomiting.\n\n2. Remove the Allergen (if possible): If the allergic reaction is caused by something like food or a bee sting, remove the source if it’s still present (e.g., remove the stinger with a flat object).\n\n3. Administer Antihistamines: If the reaction is mild and the person has antihistamines available, help them take the medication to reduce symptoms like itching and swelling.\n\n4. Use an EpiPen (if available): For severe allergic reactions (anaphylaxis), administer an EpiPen (epinephrine auto-injector) if the person has one. Inject it into the outer thigh, and hold it in place for 3 seconds.\n\n5. Call for Emergency Help: Even if the EpiPen has been used, call emergency services immediately, as further treatment may be needed.\n\n6. Monitor Breathing and Pulse: Stay with the person, monitor their breathing, and be prepared to perform CPR if they become unresponsive.\n\nRecommended Medications for Allergic Reactions:\n- Antihistamines: Such as diphenhydramine (Benadryl) for mild allergic reactions.\n- Epinephrine (EpiPen): For severe allergic reactions (anaphylaxis), administered via auto-injector.\n\nIndication of Nearby Hospital: If the allergic reaction is severe or does not improve with medication, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "eye_injury":
        return "First Aid for Eye Injury\n\nStep by Step First Aid Instructions:\n\n1. Assess the Injury: Determine the type of injury (e.g., foreign object, chemical exposure, or physical trauma). For chemical exposure, immediately flush the eye with clean water for at least 15 minutes. For a foreign object, avoid rubbing the eye. Blink repeatedly to see if the object can be naturally removed.\n\n2. Flush the Eye with Water: Rinse the eye with cool, clean water for 15 minutes if a foreign object, chemical, or irritant is in the eye. Do not use any other solutions except clean water or saline.\n\n3. Cover the Eye: If there’s severe pain, bleeding, or if the object cannot be removed, cover the injured eye with a sterile gauze or clean cloth. Do not apply pressure to the eye.\n\n4. Seek Medical Attention: Call emergency services if the eye injury is serious, such as if it involves chemical burns or objects penetrating the eye. Avoid attempting to remove embedded objects"
    elif intent == "hypoglycemia":
        return "First Aid for Hypoglycemia (Low Blood Sugar)\n\nStep by Step First Aid Instructions:\n\n1. Identify Symptoms: Look for symptoms like shakiness, sweating, confusion, rapid heartbeat, dizziness, and irritability.\n\n2. Provide Sugar Immediately: If the person is conscious, give them something sugary to quickly raise blood sugar levels. Examples include: 3-4 glucose tablets, 1/2 cup of fruit juice or regular soda (not diet), 1 tablespoon of honey or sugar, hard candy (if nothing else is available).\n\n3. Wait and Recheck: Wait about 15 minutes after giving sugar. Recheck the blood sugar level if possible. If the person still feels symptoms, provide more sugar.\n\n4. Keep the Person Calm: Have them sit or lie down and monitor their condition. Once their blood sugar level rises, encourage them to eat a more substantial snack like crackers with peanut butter to prevent further drops.\n\n5. Seek Medical Help if Severe: If the person becomes unconscious or cannot swallow, call emergency services immediately. Do not attempt to give food or drink. If available, administer a glucagon injection.\n\nRecommended Medications for Hypoglycemia:\n- Glucose Tablets/Gels: To quickly raise blood sugar levels.\n- Glucagon Injection: Used for severe cases where the person is unconscious or unable to swallow (after medical consultation).\n\nIndication of Nearby Hospital: If the hypoglycemia is severe or symptoms persist, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "hyperglycemia":
        return "First Aid for Hyperglycemia (High Blood Sugar)\n\nStep by Step First Aid Instructions:\n\n1. Identify Symptoms: Common symptoms include excessive thirst, frequent urination, dry mouth, weakness, and blurred vision.\n\n2. Check Blood Sugar: If the person has a blood glucose meter, have them check their blood sugar level. If it’s above their target range, follow the steps below.\n\n3. Encourage Hydration: Have the person drink water to help flush excess sugar from the bloodstream and prevent dehydration.\n\n4. Administer Insulin (if prescribed): If the person takes insulin, assist them in administering the appropriate dose to bring down their blood sugar level (as per their doctor's guidance).\n\n5. Monitor for Worsening Symptoms: If the person’s condition worsens or if they show signs of diabetic ketoacidosis (nausea, vomiting, fruity breath, confusion), seek medical attention immediately.\n\n6. Seek Medical Attention: If the person cannot manage their symptoms or if their blood sugar continues to rise, call emergency services.\n\nRecommended Medications for Hyperglycemia:\n- Insulin: For those who take insulin to manage diabetes, it should be administered per their prescribed regimen.\n\nIndication of Nearby Hospital: If hyperglycemia is severe or accompanied by symptoms like confusion or vomiting, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "drug_overdose":
        return "First Aid for Drug Overdose\n\nStep by Step First Aid Instructions:\n\n1. Call for Emergency Help: Immediately call emergency services if you suspect someone has overdosed. Provide the operator with as much information as possible about the substance involved.\n\n2. Check Responsiveness: If the person is conscious, keep them calm and encourage them to stay awake. If they are unconscious but breathing, place them in the recovery position (on their side with the head slightly tilted) to prevent choking.\n\n3. Administer Naloxone (if available): If you suspect an opioid overdose (e.g., heroin or prescription painkillers), administer naloxone if available. This can temporarily reverse the effects of an opioid overdose.\n\n4. Perform CPR (if necessary): If the person stops breathing or has no pulse, begin CPR immediately. Continue until emergency services arrive.\n\n5. Avoid Inducing Vomiting: Do not attempt to make the person vomit, as this can cause further complications, especially if they are unconscious.\n\n6. Provide Reassurance: If the person is conscious, stay with them, keep them calm, and provide reassurance until help arrives.\n\nRecommended Medications for Drug Overdose:\n- Naloxone: Used to reverse opioid overdoses.\n- Activated Charcoal: May be administered by medical professionals in some cases to absorb drugs in the stomach (under medical guidance).\n\nIndication of Nearby Hospital: If drug overdose symptoms persist or the person remains unconscious, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "nose_injury":
        return "First Aid for Nose Injury (Broken Nose)\n\nStep by Step First Aid Instructions:\n\n1. Control the Bleeding: Have the person sit upright and lean forward slightly to avoid swallowing blood. Pinch the soft part of the nose (just below the bony part) and apply pressure for 10-15 minutes.\n\n2. Apply Cold Compress: Apply a cold compress or ice pack to the nose and surrounding area to reduce swelling. Do not apply ice directly to the skin; wrap it in a cloth first.\n\n3. Avoid Manipulating the Nose: Do not try to straighten or manipulate the nose yourself. Keep it in its current position and avoid touching it.\n\n4. Monitor Breathing: Ensure the person can breathe through their mouth if their nose is blocked or painful to breathe through.\n\n5. Seek Medical Attention: If the nose appears deformed, there’s severe swelling, or difficulty breathing through the nose, seek medical attention promptly.\n\nRecommended Medications for Nose Injury (Broken Nose):\n- Over-the-counter pain relievers: Ibuprofen or acetaminophen to manage pain and swelling.\n\nIndication of Nearby Hospital: If the nose injury is severe or accompanied by breathing difficulty, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "throat_injury":
        return "First Aid for Throat Injury\n\nStep by Step First Aid Instructions:\n\n1. Assess Breathing and Consciousness: Check if the person is breathing normally and conscious. If there is any difficulty breathing, coughing up blood, or unconsciousness, call emergency services immediately.\n\n2. Apply Cold Compress: If the injury involves external bruising or swelling, apply a cold compress to the neck area to reduce swelling. Do not apply ice directly to the skin.\n\n3. Keep the Person Calm and Still: Encourage the person to remain calm and as still as possible to avoid aggravating the injury. Avoid talking or swallowing excessively.\n\n4. Monitor for Breathing Issues: Watch for signs of respiratory distress, such as wheezing, shortness of breath, or inability to speak.\n\n5. Do Not Apply Pressure to the Throat: Avoid applying any pressure to the neck or throat area, as it may worsen the injury.\n\n6. Seek Medical Attention: Even if the injury seems minor, it’s important to seek medical evaluation to rule out internal damage.\n\nRecommended Medications for Throat Injury:\n- Pain relievers: Ibuprofen or acetaminophen for pain management (under medical guidance).\n\nIndication of Nearby Hospital: If the throat injury causes difficulty breathing or any concerning symptoms, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "rib_injury":
        return "First Aid for Rib Injury\n\nStep by Step First Aid Instructions:\n\n1. Help the Person Sit Upright: Encourage the person to sit upright, as this will make breathing easier and reduce discomfort.\n\n2. Apply Cold Compress: Apply a cold compress or ice pack to the injured area for 20 minutes every hour to help reduce swelling and pain. Ensure the ice is wrapped in a cloth.\n\n3. Support Breathing: Encourage slow, deep breaths to avoid lung complications like pneumonia, which can develop if the person takes shallow breaths due to pain.\n\n4. Avoid Wrapping or Bandaging: Do not tightly wrap or bind the ribs. This can restrict breathing and increase the risk of lung infection.\n\n5. Seek Medical Attention: If the pain is severe, there is difficulty breathing, or the person feels faint or dizzy, seek medical help immediately.\n\nRecommended Medications for Rib Injury: Over the counter pain relievers: Ibuprofen or acetaminophen can help manage the pain and reduce inflammation.\n\nIndication of Nearby Hospital: If the rib injury is severe or accompanied by difficulty breathing or dizziness, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "pelvic_injury":
        return "First Aid for Pelvic Injury\n\nStep by Step First Aid Instructions:\n\n1. Keep the Person Still: Do not move the person unless absolutely necessary, as pelvic injuries can lead to serious internal bleeding or organ damage. Keep them lying flat and still.\n\n2. Call for Emergency Help: Immediately call emergency services. Pelvic injuries require prompt medical attention, often in a hospital setting.\n\n3. Immobilize the Pelvic Area: If possible, use a folded blanket or towel placed under the knees to slightly elevate the legs and stabilize the pelvis.\n\n4. Monitor for Shock: Look for signs of shock, such as pale, clammy skin, rapid heartbeat, or confusion. If signs of shock are present, keep the person warm and continue monitoring their condition.\n\n5. Avoid Giving Food or Drink: Do not give the injured person any food or drinks, as they may need surgery and should have an empty stomach.\n\nRecommended Medications for Pelvic Injury: Pain relief: Pain medications should only be given under medical supervision due to the severity of the injury.\n\nIndication of Nearby Hospital: Pelvic injuries can be life-threatening, so it’s crucial to seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "hip_dislocation":
        return "First Aid for Hip Dislocation\n\nStep by Step First Aid Instructions:\n\n1. Do Not Attempt to Relocate the Joint: Do not try to pop the hip back into place. This requires professional medical attention to avoid further injury.\n\n2. Keep the Person Still: Help the person lie down on their back, keeping the affected leg in the position it was found. Do not move or rotate the leg.\n\n3. Immobilize the Leg: Use a blanket, towels, or pillows to support and immobilize the leg, keeping it still until help arrives.\n\n4. Call for Emergency Help: Immediately call emergency services. A hip dislocation is a serious injury that requires urgent medical attention to prevent long-term damage.\n\n5. Monitor for Shock: Check for signs of shock, such as pale skin, rapid breathing, or confusion. If these symptoms appear, keep the person warm and continue monitoring them.\n\nRecommended Medications for Hip Dislocation: Pain relief: Medications like ibuprofen or acetaminophen should only be given under medical supervision, as the person may need surgery or other treatment.\n\nIndication of Nearby Hospital: Hip dislocations require urgent medical care. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for immediate care."
    elif intent == "shoulder_dislocation":
        return "First Aid for Shoulder Dislocation\n\nStep by Step First Aid Instructions:\n\n1. Do Not Force the Joint Back: Do not attempt to force the shoulder back into place. This can cause more damage to the surrounding muscles, nerves, and blood vessels.\n\n2. Immobilize the Arm: Support the affected arm in the most comfortable position, using a sling, bandage, or even a piece of clothing. Secure the arm against the body.\n\n3. Apply a Cold Compress: Gently place a cold compress or ice pack wrapped in a cloth on the shoulder to reduce swelling and pain. Apply for 15-20 minutes at a time.\n\n4. Seek Medical Attention: Go to the nearest hospital or call emergency services for professional help to relocate the joint.\n\n5. Monitor for Circulation Issues: Check the affected arm and hand for circulation issues, such as numbness, tingling, or loss of color. These could indicate nerve or blood vessel damage.\n\nRecommended Medications for Shoulder Dislocation: Over the counter pain relievers: Ibuprofen or acetaminophen can help manage pain and reduce inflammation until medical help is available.\n\nIndication of Nearby Hospital: Shoulder dislocations need prompt medical evaluation to avoid further complications. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for a vehicle and proceed to the hospital for professional care."
    elif intent == "knee_dislocation":
        return "First Aid for Knee Dislocation\n\nStep by Step First Aid Instructions:\n\n1. Do Not Attempt to Relocate the Knee: Avoid trying to push or force the knee back into place, as this could worsen the injury.\n\n2. Keep the Person Still: Help the person stay in a comfortable position and avoid moving the leg. If possible, have them lie flat and elevate the leg slightly, without moving the knee joint.\n\n3. Immobilize the Leg: Use a splint or padded material (like towels or blankets) to support the leg and prevent movement. Secure it loosely with a bandage or cloth.\n\n4. Apply a Cold Compress: Apply a cold compress or ice pack wrapped in a cloth to the knee to reduce swelling and pain. Do not apply ice directly to the skin.\n\n5. Call for Emergency Help: Immediately call emergency services, as knee dislocations can damage blood vessels, nerves, and ligaments, requiring urgent medical care.\n\nRecommended Medications for Knee Dislocation: Pain relief: Over the counter medications like ibuprofen or acetaminophen may be used to manage pain but should only be given after consulting a medical professional.\n\nIndication of Nearby Hospital: Knee dislocations are serious injuries. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "finger_dislocation":
        return "First Aid for Finger Dislocation\n\nStep by Step First Aid Instructions:\n\n1. Do Not Try to Relocate the Finger: Do not attempt to pull or push the finger back into place. Improper handling can damage surrounding tissues.\n\n2. Immobilize the Finger: Gently wrap the finger in a soft cloth or bandage to immobilize it. You can tape the dislocated finger to an adjacent finger (buddy taping) to provide support.\n\n3. Apply a Cold Compress: Apply a cold compress or ice pack wrapped in a cloth to the finger for 15-20 minutes to reduce swelling and pain.\n\n4. Seek Medical Attention: Visit a healthcare provider as soon as possible to have the finger properly relocated and to assess for fractures or ligament damage.\n\n5. Monitor for Circulation Issues: Check the finger for numbness, discoloration, or tingling, which could indicate compromised blood flow. If these symptoms appear, seek emergency medical care immediately.\n\nRecommended Medications for Finger Dislocation: Over the counter pain relievers: Ibuprofen or acetaminophen can help relieve pain and swelling.\n\nIndication of Nearby Hospital: If the finger remains dislocated or shows signs of severe swelling, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance services are delayed, arrange transportation to the hospital for professional care."
    elif intent == "torn_ligament":
        return "First Aid for Torn Ligament\n\nStep by Step First Aid Instructions:\n\n1. Stop Activity Immediately: If the injury occurs during physical activity, stop moving the affected area right away to prevent further damage.\n\n2. Rest the Area: Keep the injured area immobile and avoid putting weight on it. Rest the joint or limb as much as possible.\n\n3. Apply Ice: Use an ice pack or cold compress wrapped in a cloth to reduce swelling. Apply it for 15-20 minutes every 1-2 hours during the first 48 hours.\n\n4. Compression: Wrap the injured area with a bandage or compression wrap to help reduce swelling. Ensure it's not too tight to avoid cutting off circulation.\n\n5. Elevation: Raise the injured limb above heart level, using pillows to support it, to further reduce swelling.\n\n6. Seek Medical Attention: If the pain is severe, or if there is swelling and difficulty moving the joint, consult a healthcare provider for further evaluation and treatment.\n\nRecommended Medications for Torn Ligament: Pain relievers: Over the counter medications like ibuprofen or acetaminophen can help reduce pain and inflammation.\n\nIndication of Nearby Hospital: If the eye infection becomes severe, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If ambulance arrival is delayed, arrange for a vehicle and proceed to the hospital for urgent care."
    elif intent == "alcohol_poisoning":
        return "First Aid for Alcohol Poisoning\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Recognize signs of alcohol poisoning, such as confusion, vomiting, seizures, slow or irregular breathing, pale or bluish skin, and unconsciousness. Determine if the person is responsive.\n\n2. Call for Emergency Help: If alcohol poisoning is suspected, call emergency services immediately, as it can be life-threatening.\n\n3. Keep the Person Awake and Sitting Up: If the person is conscious, try to keep them awake and sitting up to prevent choking on vomit. Do not allow them to lie down.\n\n4. Monitor Breathing and Pulse: Continuously monitor their breathing and pulse. If breathing is slow or stops, begin CPR if trained to do so.\n\n5. Do Not Leave Them Alone: Stay with the person until help arrives. They may lose consciousness, and it's crucial to keep an eye on their condition.\n\n6. Place Them in the Recovery Position: If they become unconscious but are still breathing, place them on their side with their knees bent to prevent choking.\n\nRecommended Medications and Ointments: None: There are no specific medications for alcohol poisoning that can be administered outside a medical setting. Supportive care is crucial.\n\nNeeded Materials: Phone: To call emergency services. Cold Compress: To help keep the person awake if needed. First Aid Kit: For general first aid supplies.\n\nIndication of Nearby Hospital: If the person remains unresponsive or symptoms do not improve, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "chest_pain":
        return "First Aid for Chest Pain\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Ask the person to describe the pain (sharp, dull, pressure) and its location. Determine if the pain is severe, sudden, or accompanied by other symptoms like shortness of breath, sweating, nausea, or dizziness.\n\n2. Keep the Person Calm: Encourage the person to remain calm and sit down in a comfortable position. Stress can worsen the symptoms.\n\n3. Loosen Tight Clothing: If possible, loosen any tight clothing to help the person breathe easier.\n\n4. Call for Emergency Help: If the pain is severe, persistent, or accompanied by alarming symptoms (like difficulty breathing, confusion, or significant sweating), call emergency services immediately.\n\n5. Administer Aspirin (if appropriate): If the person is conscious and not allergic, you may give them an aspirin (325 mg) to chew. This can help thin the blood and improve blood flow to the heart. However, do not administer aspirin if the person has a history of bleeding disorders or has been advised against it by a healthcare provider.\n\n6. Monitor Their Condition: Keep an eye on their symptoms while waiting for emergency services. If they become unresponsive or stop breathing, begin CPR if trained to do so.\n\nRecommended Medications and Ointments: Aspirin: 325 mg, if appropriate. Pain Relievers: Over-the-counter medications may be used if the pain is mild and not related to any serious condition.\n\nNeeded Materials: Phone: To call emergency services. Aspirin: If the person can take it. First Aid Kit: For general first aid supplies.\n\nIndication of Nearby Hospital: If the chest pain is severe or accompanied by concerning symptoms, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "dental_emergencies":
        return "First Aid for Dental Emergencies\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Identify the type of dental emergency (tooth knocked out, chipped, broken, or severe toothache).\n\n2. For a Knocked Out Tooth: Rinse the tooth gently with water if dirty, but do not scrub it. Try to place the tooth back into the socket, making sure it is facing the right way. If this is not possible, keep the tooth moist by placing it in milk or saliva.\n\n3. For a Chipped or Broken Tooth: Rinse the mouth with warm water to clean the area. Apply a cold compress to the outside of the cheek or mouth near the broken tooth to reduce swelling.\n\n4. For Severe Toothache: Rinse the mouth with warm salt water. Gently floss to remove any debris between teeth. Apply a cold compress to the cheek if there is swelling.\n\n5. Seek Immediate Dental Care: Contact a dentist as soon as possible for any of the above emergencies.\n\nRecommended Medications and Ointments: Pain Relievers: Over-the-counter painkillers like ibuprofen or acetaminophen for pain relief. Clove Oil: Can be applied to a cotton ball and placed on the painful tooth for temporary pain relief.\n\nNeeded Materials: Milk or Saliva Container: To store a knocked-out tooth. Cold Compress: For swelling. Floss: To clear debris. First Aid Kit: For basic supplies.\n\nIndication of Nearby Hospital: If the dental injury is severe or accompanied by alarming symptoms like uncontrollable bleeding or significant swelling, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "ear_injury":
        return "First Aid for Ear Injury\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Check if the injury involves a cut, blow to the ear, or objects lodged inside. Determine if there is bleeding, swelling, hearing loss, or pain.\n\n2. For Bleeding from the Ear: If bleeding is present, cover the ear with a clean cloth or sterile gauze, and apply gentle pressure to stop the bleeding. Do not insert anything into the ear.\n\n3. For Objects in the Ear: Do not try to remove the object with tweezers or a cotton swab, as this could push it deeper. Tilt the head to the side and gently shake, hoping the object falls out. If unsuccessful, seek medical assistance.\n\n4. For Ear Trauma from a Blow: Apply a cold compress to reduce swelling. If hearing loss or severe pain persists, seek medical attention.\n\n5. Seek Medical Help for Serious Injuries: If there is persistent bleeding, hearing loss, or severe pain, seek immediate medical attention.\n\nRecommended Medications and Ointments: Pain Relievers: Ibuprofen or acetaminophen can be used to relieve pain. Antibiotic Ointment: For cuts or external injuries to the ear.\n\nNeeded Materials: Clean Cloth or Sterile Gauze: To control bleeding. Cold Compress: To reduce swelling. Antibiotic Ointment: For external cuts. First Aid Kit: For basic supplies.\n\nIndication of Nearby Hospital: If the ear injury is severe or accompanied by hearing loss or significant pain, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "insert_stings":
        return "First Aid for Insect Stings\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Check for signs of an allergic reaction such as difficulty breathing, swelling of the face, lips, or throat, or dizziness. These require immediate medical attention.\n\n2. Remove the Stinger: If the stinger is still visible (such as from a bee), remove it by scraping it out with a flat edge (e.g., a credit card). Do not use tweezers, as this may squeeze more venom into the skin.\n\n3. Clean the Area: Wash the sting site with soap and water to prevent infection.\n\n4. Apply Cold Compress: Use a cold compress or ice pack to reduce swelling and pain.\n\n5. Monitor for Symptoms: Keep an eye on the sting area for signs of infection, such as redness, swelling, or pus, and for any symptoms of an allergic reaction.\n\n6. Seek Medical Help if Severe Reaction Occurs: If the person experiences difficulty breathing, swelling, or signs of anaphylaxis, call emergency services immediately and, if available, administer an epinephrine auto injector (EpiPen).\n\nRecommended Medications and Ointments:\n- Antihistamines: Over the counter antihistamines like diphenhydramine (Benadryl) can help reduce swelling and itching.\n- Hydrocortisone Cream or Calamine Lotion: Can be applied to the sting site to reduce itching and inflammation.\n- Pain Relievers: Ibuprofen or acetaminophen to relieve pain.\n\nNeeded Materials:\n- Flat Edge (Credit Card): To scrape out the stinger.\n- Cold Compress or Ice Pack: To reduce swelling.\n- Antihistamine: For allergic reactions.\n- First Aid Kit: For general supplies like antiseptic wipes and bandages.\n\nIndication of Nearby Hospital: If the sting is severe or accompanied by an allergic reaction, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "animal_bites":
        return "First Aid for Animal Bites\n\nStep by Step First Aid Instructions:\n\n1. Assess the Situation: Determine the severity of the bite and whether the animal was wild or domestic. If the animal might have rabies or the bite is deep, seek medical help immediately.\n\n2. Control Bleeding: If the bite is bleeding heavily, apply direct pressure to the wound with a clean cloth or sterile gauze.\n\n3. Clean the Wound: Wash the bite area thoroughly with soap and water for at least five minutes to remove bacteria and reduce the risk of infection.\n\n4. Apply a Sterile Bandage: After cleaning the wound, apply a sterile bandage or clean dressing to cover it.\n\n5. Monitor for Infection: Watch for signs of infection, such as redness, swelling, warmth, or pus at the bite site. If any of these symptoms occur, seek medical attention.\n\n6. Seek Immediate Medical Help if Necessary: Seek immediate medical attention if the bite is deep, if the animal's rabies vaccination status is unknown, or if the person hasn’t had a tetanus shot in the last 10 years.\n\nRecommended Medications and Ointments:\n- Antibiotics: A healthcare professional may prescribe antibiotics to prevent or treat infections, especially for deep bites.\n- Tetanus Shot: If the person’s tetanus vaccination is outdated, a booster shot may be needed.\n- Rabies Vaccine: May be required if the bite was from an unvaccinated or wild animal.\n- Antibiotic Ointment: Apply to minor bites after cleaning to prevent infection.\n\nNeeded Materials:\n- Clean Cloth or Sterile Gauze: To stop the bleeding.\n- Soap and Water: For cleaning the wound.\n- Sterile Bandages: To cover the bite.\n- First Aid Kit: For general supplies.\n\nIndication of Nearby Hospital: If the animal bite is severe or accompanied by signs of infection, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "snake_bite":
        return "First Aid for Snake Bite\n\nStep by Step First Aid Instructions:\n\n1. Move the Person to Safety: Move away from the snake to avoid additional bites, but try to note its appearance for identification.\n\n2. Keep the Person Calm and Still: Encourage the person to stay calm and lie down, keeping the bite area below the heart level to slow the spread of venom.\n\n3. Do Not Apply a Tourniquet or Ice: Do not apply a tourniquet, ice, or attempt to suck out the venom as these actions can cause more harm.\n\n4. Clean the Bite Area: Gently wash the bite area with soap and water. Do not rub it, as this can increase venom spread.\n\n5. Immobilize the Affected Limb: Use a splint or any rigid object to immobilize the bitten limb and reduce movement.\n\n6. Seek Immediate Medical Attention: Call emergency services or get the person to a hospital as quickly as possible for antivenom treatment. Time is critical.\n\nRecommended Medications and Ointments:\n- Antivenom: Only available in a hospital setting and must be administered by a healthcare professional.\n- Pain Relievers: Ibuprofen or acetaminophen may be used for pain relief if advised by medical professionals after the bite is treated.\n\nNeeded Materials:\n- Splint or Rigid Object: To immobilize the bitten limb.\n- Soap and Water: To clean the bite site.\n- First Aid Kit: For basic supplies like bandages.\n\nIndication of Nearby Hospital: If the snake bite is from a venomous snake or the person shows severe symptoms like difficulty breathing, weakness, or swelling, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "spider_bite":
        return "First Aid for Spider Bite\n\nStep by Step First Aid Instructions:\n\n1. Assess the Bite: Identify if the bite is from a potentially dangerous spider (such as a black widow or brown recluse). Symptoms may include pain, swelling, cramping, or a spreading rash.\n\n2. Clean the Bite Area: Wash the area with soap and water to reduce the risk of infection.\n\n3. Apply a Cold Compress: Use a cold compress or ice pack to reduce swelling and pain. Avoid applying ice directly to the skin.\n\n4. Elevate the Affected Limb: Keep the affected limb elevated to reduce swelling.\n\n5. Monitor for Symptoms: Watch for worsening symptoms like severe pain, difficulty breathing, or spreading redness. If these symptoms occur, seek medical help immediately.\n\n6. Seek Medical Help for Severe Bites: If the bite is from a dangerous spider or the person is showing severe symptoms, get medical help right away.\n\nRecommended Medications and Ointments:\n- Antihistamines: Over the counter antihistamines like diphenhydramine (Benadryl) can help reduce itching and swelling.\n- Pain Relievers: Ibuprofen or acetaminophen can help manage pain.\n- Antibiotic Ointment: For minor bites to prevent infection.\n- Antivenom: Available at hospitals for certain venomous spiders.\n\nNeeded Materials:\n- Cold Compress or Ice Pack: To reduce swelling.\n- Soap and Water: To clean the bite area.\n- First Aid Kit: For general supplies.\n\nIndication of Nearby Hospital: If the spider bite is from a venomous species or is accompanied by severe symptoms, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "scorpion_sting":
        return "First Aid for Scorpion Sting\n\nStep by Step First Aid Instructions:\n\n1. Assess the Sting: Check for symptoms of a severe reaction, such as difficulty breathing, muscle twitching, or abnormal eye movements. These symptoms require immediate medical attention.\n\n2. Clean the Sting Area: Wash the sting site with soap and water to reduce the risk of infection.\n\n3. Apply a Cold Compress: Use a cold compress or ice pack to reduce pain and swelling. Do not apply ice directly to the skin.\n\n4. Keep the Person Calm: Encourage the person to remain calm and still, as movement can spread venom faster through the body.\n\n5. Seek Medical Help if Severe Symptoms Occur: Call emergency services if the person shows severe symptoms like difficulty breathing, seizures, or severe pain.\n\nRecommended Medications and Ointments:\n- Antihistamines: For reducing swelling and itching in mild cases.\n- Pain Relievers: Ibuprofen or acetaminophen can help with pain management.\n- Antivenom: For severe scorpion stings, only administered in hospitals.\n\nNeeded Materials:\n- Cold Compress or Ice Pack: To reduce pain and swelling.\n- Soap and Water: To clean the sting area.\n- First Aid Kit: For basic supplies like bandages.\n\nIndication of Nearby Hospital: If the scorpion sting is severe or accompanied by serious symptoms, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "jellyfish_sting":
        return "First Aid for Jellyfish Sting\n\nStep by Step First Aid Instructions:\n\n1. Remove the Person from the Water: Get the person out of the water and away from the jellyfish.\n\n2. Rinse with Vinegar or Saltwater: Rinse the affected area with vinegar (or seawater if vinegar is not available) to neutralize the venom. Avoid using freshwater, as this can cause the release of more venom.\n\n3. Remove Tentacles Carefully: Use tweezers or the edge of a credit card to carefully remove any remaining tentacles stuck to the skin. Avoid using bare hands.\n\n4. Soak in Hot Water: Soak the affected area in hot water (not scalding) for 20-45 minutes to relieve pain. If a hot water soak is not possible, apply a hot compress.\n\n5. Seek Medical Attention if Symptoms Persist: If the sting causes difficulty breathing, chest pain, or severe pain, seek medical help immediately.\n\nRecommended Medications and Ointments:\n- Pain Relievers: Ibuprofen or acetaminophen can help relieve pain.\n- Antihistamines: For reducing swelling and itching.\n\nNeeded Materials:\n- Vinegar or Seawater: To rinse the affected area.\n- Tweezers or Credit Card: To remove tentacles.\n- Hot Water or Hot Compress: To relieve pain.\n\nIndication of Nearby Hospital: If the jellyfish sting is severe or causes systemic symptoms like difficulty breathing or severe pain, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "tick_bite":
        return "First Aid for Tick Bite\n\nStep by Step First Aid Instructions:\n\n1. Remove the Tick Carefully: Use fine-tipped tweezers to grasp the tick as close to the skin as possible. Pull upwards with steady pressure. Do not twist or jerk the tick, as this may cause parts to break off and remain in the skin.\n\n2. Clean the Bite Area: After removing the tick, clean the bite area and your hands with soap and water or an antiseptic wipe.\n\n3. Dispose of the Tick: Place the tick in a sealed bag or container, or flush it down the toilet. Do not crush it with your fingers.\n\n4. Monitor for Symptoms: Watch for signs of illness in the following days, such as fever, rash, fatigue, or joint pain. These may indicate a tick-borne disease, such as Lyme disease.\n\n5. Seek Medical Attention if Symptoms Occur: If you notice a rash, fever, or other symptoms, seek medical attention promptly.\n\nRecommended Medications and Ointments:\n- Antibiotics: May be prescribed if Lyme disease or another tick-borne illness is suspected.\n- Antiseptic Cream: For cleaning and protecting the bite area.\n- Pain Relievers: Ibuprofen or acetaminophen to manage any discomfort.\n\nNeeded Materials:\n- Fine-Tipped Tweezers: For tick removal.\n- Soap and Water or Antiseptic Wipes: To clean the bite area.\n- First Aid Kit: For general supplies.\n\nIndication of Nearby Hospital: If the tick bite leads to a rash, fever, or other concerning symptoms, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed in arriving, it’s crucial that you take immediate action to ensure the person receives the care they need. Please arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure they get the necessary medical attention as quickly as possible."
    elif intent == "human_bite":
        return "First Aid for Human Bite\n\nStep by Step First Aid Instructions:\n\n1. Assess the Severity of the Bite: Check if the skin is broken. Human bites carry a high risk of infection due to bacteria in the mouth.\n\n2. Clean the Wound Thoroughly: Wash the bite area with soap and water for at least 5 minutes. Rinse thoroughly to remove bacteria and dirt.\n\n3. Apply an Antiseptic: After cleaning, apply an antiseptic solution or ointment to prevent infection.\n\n4. Cover the Wound: Cover the bite with a clean, sterile bandage to protect the wound from further contamination.\n\n5. Seek Medical Attention if Necessary: If the bite is deep, bleeding heavily, or shows signs of infection (redness, swelling, warmth), seek medical attention promptly.\n\nRecommended Medications and Ointments:\n- Antibiotics: A doctor may prescribe antibiotics to prevent or treat infection.\n- Tetanus Shot: If the bite punctured the skin and the person hasn't had a recent tetanus shot, a booster may be necessary.\n- Antiseptic Cream: To prevent infection.\n- Pain Relievers: Ibuprofen or acetaminophen to manage pain.\n\nNeeded Materials:\n- Soap and Water: To clean the wound.\n- Antiseptic Solution or Ointment: To prevent infection.\n- Sterile Bandages: To cover the wound.\n\nIndication of Nearby Hospital: If the bite causes deep tissue damage, severe bleeding, or signs of infection, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, it’s crucial that you take immediate action. Arrange for a vehicle promptly and proceed directly to the nearest hospital to ensure the necessary medical care is provided as quickly as possible."
    elif intent == "foreign_object_in_the_eye":
        return "First Aid for Foreign Object in the Eye\n\nStep by Step First Aid Instructions:\n\n1. Instruct the Person Not to Rub Their Eye: Rubbing the eye may cause the object to scratch the cornea or lodge further inside the eye.\n\n2. Rinse the Eye with Clean Water or Saline Solution: Hold the eyelid open and gently flush the eye with clean water or saline solution to dislodge the object.\n\n3. Check if the Object Has Been Removed: After rinsing, check if the object is still present. If it remains, do not attempt to remove it manually.\n\n4. Blink or Pull the Upper Eyelid Over the Lower Eyelid: Blinking can sometimes help dislodge small particles. Pulling the upper eyelid over the lower one may also help sweep the object away.\n\n5. Seek Medical Help if the Object Remains or Causes Pain: If the object is embedded, causes sharp pain, or is not removed by rinsing, seek medical attention immediately.\n\nRecommended Medications and Ointments:\n- Lubricating Eye Drops: Can help relieve irritation once the object is removed.\n- Antibiotic Eye Ointment: May be recommended if the object caused a scratch or injury to the eye.\n\nNeeded Materials:\n- Clean Water or Saline Solution: To rinse the eye.\n- Eye Cup or Container: For easier rinsing.\n- Sterile Bandage: To cover the eye if needed.\n\nIndication of Nearby Hospital: If the foreign object is lodged deeply, causes sharp pain, or impairs vision, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, take prompt action to ensure the person receives timely care. Arrange for a vehicle and proceed directly to the nearest hospital."
    elif intent == "heat_exhaustion":
        return "First Aid for Heat Exhaustion\n\nStep by Step First Aid Instructions:\n\n1. Move the Person to a Cooler Area: Get the person out of direct sunlight or a hot environment, and move them to a shaded, air-conditioned, or cool area.\n\n2. Have the Person Rest and Lie Down: Encourage them to lie down with their legs slightly elevated to improve circulation.\n\n3. Hydrate with Cool Water: Give the person cool water or an electrolyte drink to sip slowly. Avoid caffeinated or alcoholic beverages.\n\n4. Cool the Person’s Body: Use cool, wet cloths or towels to sponge down the body, focusing on the neck, armpits, and forehead. You can also use a fan to help cool them down.\n\n5. Seek Medical Attention if Symptoms Worsen: If symptoms like dizziness, nausea, headache, or weakness persist, or if the person begins to lose consciousness, call emergency services immediately.\n\nRecommended Medications and Ointments:\n- Electrolyte Drinks or Salt Tablets: To replenish lost salts if available.\n- Pain Relievers: Ibuprofen or acetaminophen for headaches or body aches, if recommended by a doctor.\n\nNeeded Materials:\n- Cool Water or Electrolyte Drinks: For rehydration.\n- Wet Towels or Cloths: For cooling the body.\n- Fan: To help cool down faster.\n\nIndication of Nearby Hospital: If the heat exhaustion symptoms persist or worsen, such as fainting, confusion, or vomiting, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the nearest hospital to ensure the person receives the necessary medical attention as quickly as possible."
    elif intent == "cold_exposure":
        return "First Aid for Cold Exposure (Frostbite)\n\nStep by Step First Aid Instructions:\n\n1. Move the Person to a Warmer Area: Get the person out of the cold and into a warm environment immediately to prevent further damage.\n\n2. Warm the Affected Area Gently: Soak the frostbitten area in warm (not hot) water for 20-30 minutes. Do not use direct heat such as a fire or heating pad, as this can cause burns.\n\n3. Avoid Rubbing or Massaging the Area: Do not rub the affected area, as this can cause further tissue damage.\n\n4. Keep the Person Warm: Provide warm, dry clothing and blankets to the person to raise their overall body temperature.\n\n5. Seek Medical Attention for Severe Frostbite: If the frostbite is severe, such as numbness, hard or blistering skin, or signs of hypothermia (shivering, confusion, slurred speech), seek immediate medical attention.\n\nRecommended Medications and Ointments:\n- Pain Relievers: Ibuprofen or acetaminophen to help with pain management.\n- Antibiotic Cream: May be prescribed to prevent infection after severe frostbite.\n\nNeeded Materials:\n- Warm Water: For soaking frostbitten areas.\n- Blankets and Dry Clothing: To help raise body temperature.\n- Thermometer: To monitor body temperature.\n\nIndication of Nearby Hospital: If frostbite is severe or accompanied by signs of hypothermia, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the nearest hospital to ensure the affected person receives urgent care for cold exposure."
    elif intent == "panic_attack":
        return "First Aid for Panic Attack\n\nStep by Step First Aid Instructions:\n\n1. Stay Calm and Reassure the Person: Speak calmly and reassure the person that they are experiencing a panic attack, which, although scary, is not life-threatening.\n\n2. Encourage Slow, Deep Breaths: Guide the person to take slow, deep breaths to help them calm down. Breathing exercises like inhaling for 4 counts, holding for 4, and exhaling for 4 can help.\n\n3. Create a Calm Environment: Move the person to a quiet and less stimulating environment, if possible, to help them feel safe.\n\n4. Grounding Techniques: Encourage them to focus on their senses (e.g., describe what they can see, hear, or touch) to distract from overwhelming thoughts.\n\n5. Seek Medical Help if the Symptoms Persist or Worsen: If the panic attack lasts longer than 20 minutes or the person is unable to calm down, seek medical help.\n\nRecommended Medications and Ointments:\n- Anti-Anxiety Medications: A doctor may prescribe medications like benzodiazepines for severe panic disorders, but these are not used in immediate first aid.\n\nNeeded Materials:\n- None Specific: Calm environment and reassurance are the most critical tools.\n\nIndication of Nearby Hospital: If the panic attack is prolonged or the person becomes unresponsive, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If transportation is needed, arrange for a vehicle to ensure they receive prompt care."
    elif intent == "shock":
        return "First Aid for Shock (Hypovolemic)\n\nStep by Step First Aid Instructions:\n\n1. Lay the Person Down and Elevate Legs:\n   Have the person lie down on their back and elevate their legs about 12 inches to improve blood flow to vital organs.\n\n2. Keep the Person Warm:\n   Cover the person with a blanket to maintain body heat and prevent hypothermia.\n\n3. Do Not Give Food or Drink:\n   Avoid giving the person anything to eat or drink, as they may need surgery or other interventions.\n\n4. Control Any External Bleeding:\n   If the person is bleeding, apply pressure to the wound to stop the bleeding. Use a clean cloth or bandage.\n\n5. Seek Immediate Medical Attention:\n   Shock is a medical emergency, so call emergency services right away. Keep monitoring the person's breathing and pulse until help arrives.\n\nRecommended Medications and Ointments:\n  None for First Aid: Medical intervention is required for treatment. Fluids or blood transfusions may be given at the hospital.\n\nNeeded Materials:\n  - Blankets or Clothing: To maintain body temperature.\n  - Sterile Bandages: To control bleeding if necessary.\n\nIndication of Nearby Hospital:\n  Hypovolemic shock is life-threatening and requires immediate medical intervention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the nearest hospital to ensure the person receives critical care as soon as possible."
    elif intent == "sepsis":
        return "First Aid for Sepsis\n\nStep by Step First Aid Instructions:\n\n1. Recognize the Symptoms:\n   Look for signs of sepsis, which may include high or low body temperature, rapid breathing, elevated heart rate, confusion, and severe weakness. Sepsis is a life-threatening response to infection.\n\n2. Call Emergency Services Immediately:\n   Sepsis is a medical emergency. Call emergency services right away if you suspect sepsis.\n\n3. Monitor Vital Signs:\n   While waiting for help, monitor the person’s breathing, heart rate, and level of consciousness. If they become unresponsive, begin CPR if necessary.\n\n4. Keep the Person Comfortable:\n   Have the person lie down and keep them warm with a blanket. Do not give them anything to eat or drink.\n\n5. Provide Relevant Medical History:\n   When medical help arrives, provide any known medical history, including recent infections or surgeries, as well as current medications.\n\nRecommended Medications and Ointments:\n  None for First Aid: Antibiotics and IV fluids are essential and will be administered at the hospital. Sepsis requires professional medical treatment.\n\nNeeded Materials:\n  - Blanket or Warm Clothing: To keep the person warm.\n  - Phone: To call emergency services.\n\nIndication of Nearby Hospital:\n  Sepsis is life-threatening and requires immediate medical intervention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the nearest hospital to ensure the person receives the necessary critical care as soon as possible."
    elif intent == "sunburn":
        return "First Aid for Sunburn\n\nStep by Step First Aid Instructions:\n\n1. Get Out of the Sun Immediately:\n   Move the person to a cool, shaded area or indoors to prevent further skin damage.\n\n2. Cool the Burn:\n   Apply cool (not cold) water or compresses to the sunburned areas for 10-15 minutes. Avoid using ice, as it can further damage the skin.\n\n3. Apply Soothing Lotion:\n   Use aloe vera or a moisturizing lotion to soothe the skin and help with healing. Avoid ointments that contain petroleum, as they can trap heat in the skin.\n\n4. Stay Hydrated:\n   Encourage the person to drink plenty of water to help prevent dehydration, as sunburn can draw fluids away from the body.\n\n5. Avoid Tight Clothing:\n   Have the person wear loose, breathable clothing to avoid further irritation to the skin.\n\n6. Seek Medical Help for Severe Burns:\n   If the sunburn is severe (e.g., blisters, swelling, headache, nausea, fever), seek medical attention.\n\nRecommended Medications and Ointments:\n  - Aloe Vera Gel or Moisturizing Lotion: To soothe the skin.\n  - Over-the-Counter Pain Relievers: Ibuprofen or acetaminophen to reduce pain and inflammation.\n\nNeeded Materials:\n  - Cool Compresses: To reduce heat in the skin.\n  - Aloe Vera Gel or Lotion: To provide relief for the sunburned area.\n  - Water: For hydration.\n\nIndication of Nearby Hospital:\n  If the sunburn is severe or accompanied by symptoms like fever, nausea, or blistering, seek immediate medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the hospital for treatment."
    elif intent == "blisters":
        return "First Aid for Blisters\n\nStep by Step First Aid Instructions:\n\n1. Assess the Blister:\n   Check the size and location of the blister. If it is small and intact, it is best to leave it alone. If it is large, painful, or likely to burst, proceed carefully.\n\n2. Clean the Area:\n   Gently wash the area around the blister with soap and water. Pat the area dry with a clean towel.\n\n3. Avoid Popping the Blister:\n   Do not pop the blister unless it is large, painful, or in a location where it will likely burst on its own. If you must pop it, use a sterilized needle and do not remove the skin.\n\n4. Cover the Blister:\n   Apply a sterile bandage or blister pad to protect the area. For burst blisters, cover it with an antibiotic ointment and a clean bandage.\n\n5. Monitor for Infection:\n   Check for signs of infection such as redness, warmth, swelling, or pus. If the blister appears infected, seek medical attention.\n\nRecommended Medications and Ointments:\n  - Antibiotic Ointment: To apply on burst blisters.\n  - Over-the-Counter Pain Relievers: Ibuprofen or acetaminophen for pain management.\n\nNeeded Materials:\n  - Sterile Bandages or Blister Pads\n  - Antibiotic Ointment\n  - Soap and Water\n  - Sterilized Needle (for draining, if necessary)\n\nIndication of Nearby Hospital:\n  If the blister becomes infected or worsens, seek medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange transportation and head to the hospital for proper care."
    elif intent == "abrasions":
        return "First Aid for Abrasions (Scrapes)\n\nStep by Step First Aid Instructions:\n\n1. Clean the Wound:\n   Rinse the scrape with clean, cool water to remove dirt and debris. Use soap around, but not directly in, the wound.\n\n2. Stop the Bleeding:\n   Apply gentle pressure with a clean cloth or sterile gauze if the scrape is bleeding. Usually, abrasions do not bleed heavily.\n\n3. Apply an Antibiotic Ointment:\n   Apply a thin layer of antibiotic ointment to help prevent infection.\n\n4. Cover the Wound:\n   Use a sterile bandage or non-stick gauze pad to cover the scrape. Change the dressing daily or whenever it gets dirty or wet.\n\n5. Monitor for Infection:\n   Watch for signs of infection such as increased redness, swelling, warmth, or pus. Seek medical attention if these occur.\n\nRecommended Medications and Ointments:\n  - Antibiotic Ointment: For preventing infection.\n  - Over-the-Counter Pain Relievers: Ibuprofen or acetaminophen to relieve pain.\n\nNeeded Materials:\n  - Sterile Bandages or Non-Stick Gauze Pads\n  - Antibiotic Ointment\n  - Soap and Water\n  - Clean Cloth or Gauze (for bleeding)\n\nIndication of Nearby Hospital:\n  If the abrasion becomes infected or is large and deep, seek medical attention. Call emergency services and use our map to locate the nearest hospitals. If the ambulance is delayed, arrange for transportation and proceed directly to the hospital for proper care."








    else:
        return random.choice(responses["default"])

def save_interaction(user_input, intent):
    interaction = {"input": user_input, "intent": intent}
    try:
        with open('json/interactions.json', 'r+') as file:
            data = json.load(file)
            data['data'].append(interaction)
            file.seek(0)
            json.dump(data, file, indent=4)
    except FileNotFoundError:
        with open('json/interactions.json', 'w') as file:
            json.dump({"data": [interaction]}, file, indent=4)

def train_ml_model():
    try:
        with open('json/interactions.json', 'r') as file:
            data = json.load(file)
        if 'data' in data and len(data['data']) > 0:
            inputs = [interaction.get('input') for interaction in data['data']]
            intents = [interaction.get('intent') for interaction in data['data']]
            if len(inputs) > 0 and len(intents) > 0:
                vectorizer = CountVectorizer()
                X = vectorizer.fit_transform(inputs)
                model = MultinomialNB()
                model.fit(X, intents)
                joblib.dump(model, 'ml_model.pkl')
                joblib.dump(vectorizer, 'vectorizer.pkl')
    except FileNotFoundError:
        print("No interaction data found to train the model.")

def predict_intent(user_input):
    try:
        model = joblib.load('ml_model.pkl')
        vectorizer = joblib.load('vectorizer.pkl')
        input_vector = vectorizer.transform([user_input])
        predicted_intent = model.predict(input_vector)
        return predicted_intent[0]
    except FileNotFoundError:
        train_ml_model()            
        return "default"

@app.route('/', methods=['GET', 'POST'])
def chat():
    if request.method == 'POST':
        user_input = request.form['text_input']
        intent = analyze_input(user_input)
        save_interaction(user_input, intent)
        response = get_response(intent)
        return render_template('output.html', user_input=user_input, response=response)
    return render_template('form.html')

if __name__ == "__main__":
    app.run(debug=True)
